name: seeded_rsa
description: A library to generated RSA key pair with a string seed (prefer bip39).
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bip39: ^1.0.6
  crypto: ^3.0.2
  ninja_asn1: ^2.0.0
  ninja_prime: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
